# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
#  adapter: sqlite3
  adapter: postgresql
#  host: localhost
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  host: localhost
  database: app_development_new
  pool: 5
  username: sushi_new
  password: 1234
  encoding: utf8

test:
  <<: *default
  database: app_development_new

production:
  <<: *default
  database: db/production.sqlite3
